### ISSUE TITLE
建议可以设置书签字体大小

### ISSUE THREAD

**Issue by sweesalt** [frostime/sy-bookmark-plus#12]
建议能设置如图文字的大小：
![image](https://github.com/user-attachments/assets/32b1db6c-d517-41fd-b6c9-754217cbef38)

**Comment by frostime** [comment]
单独做一个设置我觉得没有太大必要，书签字体大小是跟着思源界面的字体大小走的。

如果有定制化需求，可以这样写一个 css 片段（改font-size），这个我后面也更到 README 文档里面好了。

```css
.b3-list-item.custom-bookmark-item {
    margin-bottom: 2px;
    font-size: 24px;
    line-height: 30px;
}
```
